### PR TITLE
Made ggev not scalar function. See #2

### PR DESCRIPTION
**Pull request by selvavm**
Modified generate.py such that `ggev` is not a scalar function

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Thank you! In #2, it is suggested that more of the arguments are non-scalar. Please take a look. What do we do about that?

**Comment by selvavm** [comment]
You are right. They should be array as well. If I remove below 2 lines, it should work,

```
        # and name in [
        #     'vl',
        #     'vr',
        # ] 
        # name.startswith('alpha') or
        # name.startswith('beta') or
```

I gave a glance and these should be an array . But wondering why it is specifically marked as scalar in the py function? Maybe my glancing missed some function which is expecting this as scalar?

**Comment by IvanUkhov** [comment]
It is hard to recall what it was made that way in the beginning. Unfortunately, someone has to go ahead and check the other functions for correctness and then remove the commented lines. Also, please rebase.

**Comment by selvavm** [comment]
Thanks! For now I will keep it commented. Now, I will have to know how to rebase :) (This is my first time)

**Comment by selvavm** [comment]
I am done with rebase as well. Thanks for your support

**Comment by IvanUkhov** [comment]
The alpha–beta change affects the following functions:

- [x] `sgges`
- [x] `sgges3`
- [x] `sggesx`
- [x] `sggev`
- [x] `sggev3`
- [x] `sggevx`
- [x] `sggsvd`
- [x] `sggsvd3`
- [x] `shgeqz`
- [ ] `slarfg`
- [x] `stgsen`
- [x] `stgsja`

The same applies to double, complex, and complex double, as well as to those ending with `_work`. One has to go over all of them and check.

**Comment by selvavm** [comment]
I checked your list and `larfg` is the affected one. Only it has Alpha as scalar and other's have an array. Any suggestion on how to modify the python script?

**Comment by IvanUkhov** [comment]
Yes, I have also gone through the list. `slarfg` is the only one that need an exception. Let me push a correction.

**Comment by selvavm** [comment]
Nevermind, I made the correction

**Comment by IvanUkhov** [comment]
All right, looks good now! Can you please pull in your local copy and then add yourself to the authors list in alphabetic order?

**Comment by selvavm** [comment]
Perfect! 

Sorry, @IvanUkhov my knowledge is limited here. Should I have to modify cargo.toml with author name? Also, should I have to rebase into 1 commit?

**Comment by IvanUkhov** [comment]
No worries! Yes, just add to `authors` in `Cargo.toml`. Nothing else is needed.

**Comment by selvavm** [comment]
I am done. And Thanks a lot @IvanUkhov for your support

**Comment by IvanUkhov** [comment]
Thank you!

**Pull request merged**
